apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- jaeger-deployment.yaml
- jaeger-service.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/managed-by: kustomize 