apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress

resources:
- nginx-deployment.yaml
- nginx-service.yaml
- nginx-configmap.yaml

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/part-of: ingress
  app.kubernetes.io/managed-by: kustomize 