apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: java-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/app/opentelemetry-javaagent.jar"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: app-config
          mountPath: /app/config
        - name: otel-agent
          mountPath: /app/opentelemetry-javaagent.jar
          subPath: opentelemetry-javaagent.jar
      volumes:
      - name: app-config
        configMap:
          name: java-app-config
      - name: otel-agent
        configMap:
          name: otel-agent-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
data:
  opentelemetry-javaagent.jar: |
    # The OpenTelemetry Java agent will be mounted here
    # You need to download and provide the agent JAR file separately 