apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: java-app
  app.kubernetes.io/part-of: user-service
  app.kubernetes.io/managed-by: kustomize 