name: kafka-user-poc
image:
  repository: kafka-user-poc
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8085

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: password 