jaeger:
  name: jaeger
  image:
    repository: jaegertracing/all-in-one
    tag: 1.42
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
    ports:
      - name: ui
        port: 16686
      - name: otlp-grpc
        port: 14250
      - name: http
        port: 14268
  env:
    COLLECTOR_OTLP_ENABLED: "true"

prometheus:
  name: prometheus
  image:
    repository: prom/prometheus
    tag: v2.45.0
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 9090
  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['kafka-user-poc:8085']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

grafana:
  name: grafana
  image:
    repository: grafana/grafana
    tag: 9.5.2
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 3000
  env:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: admin
    GF_USERS_ALLOW_SIGN_UP: "false"

loki:
  name: loki
  image:
    repository: grafana/loki
    tag: 2.8.0
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 3100
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    storage_config:
      boltdb:
        directory: /tmp/loki/index
      filesystem:
        directory: /tmp/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h 