name: CD-Hotfix Manual

on:
  workflow_dispatch:
    inputs:
      hotfix_branch:
        description: 'Branch hotfix (ex: hotfix/1.2.3)'
        required: true

permissions:
  contents: write
  packages: read
  pull-requests: write  # necessário para criar PRs

jobs:
  hotfix-release:
    runs-on: ubuntu-latest
    env:
      REGISTRY_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/kafka-user-poc

    steps:
      # 0) Validação do nome da branch
      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            if (!context.payload.inputs.hotfix_branch.startsWith('hotfix/')) {
              core.setFailed('Esta action só aceita branches hotfix/*')
            }

      # 1) Checkout do código
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2) Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3) Build e Teste
      - name: Build & Test
        run: mvn -B clean verify

      # 4) Verificar e criar PR para main se não existir
      - name: Check existing PR to main
        id: check_pr_main
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${{ github.event.inputs.hotfix_branch }}`,
              base: 'main',
              state: 'open'
            });
            
            if (prs.data.length > 0) {
              console.log(`PR já existe: #${prs.data[0].number}`);
              return prs.data[0].number;
            }
            return 0;
      
      - name: Create PR to main if not exists
        id: create_pr_main
        if: steps.check_pr_main.outputs.result == 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.event.inputs.hotfix_branch }}
          title: "Hotfix: ${{ github.event.inputs.hotfix_branch }} to main"
          body: "Aplicando hotfix na main"
          delete-branch: false
      
      # 5) Merge do PR na main
      - name: Merge PR to main
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.check_pr_main.outputs.result != 0 && steps.check_pr_main.outputs.result || steps.create_pr_main.outputs.pull-request-number }}
          merge-method: squash
      
      # ... (resto do workflow continua igual)
      
      # 9) Verificar e criar PR para develop se não existir
      - name: Check existing PR to develop
        id: check_pr_develop
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${{ github.event.inputs.hotfix_branch }}`,
              base: 'develop',
              state: 'open'
            });
            
            if (prs.data.length > 0) {
              console.log(`PR já existe: #${prs.data[0].number}`);
              return prs.data[0].number;
            }
            return 0;
      
      - name: Create PR to develop if not exists
        id: create_pr_develop
        if: steps.check_pr_develop.outputs.result == 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: ${{ github.event.inputs.hotfix_branch }}
          title: "Sync: ${{ github.event.inputs.hotfix_branch }} to develop"
          body: "Sincronizando hotfix para develop"
          delete-branch: true
      
      # 10) Merge do PR no develop
      - name: Merge PR to develop
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.check_pr_develop.outputs.result != 0 && steps.check_pr_develop.outputs.result || steps.create_pr_develop.outputs.pull-request-number }}
          merge-method: squash

      # 11) Build do Docker
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_REPO }}:${{ steps.bump_version.outputs.next-version }}
            ${{ env.REGISTRY_REPO }}:latest
