name: CD-Hotfix Manual

on:
  workflow_dispatch:
    inputs:
      hotfix_branch:
        description: 'Branch hotfix (ex: hotfix/1.2.3)'
        required: true

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  hotfix-release:
    runs-on: ubuntu-latest
    env:
      REGISTRY_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/kafka-user-poc

    steps:
      # 1) Validação do nome da branch
      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            if (!context.payload.inputs.hotfix_branch.startsWith('hotfix/')) {
              core.setFailed('Esta action só aceita branches hotfix/*')
            }

      # 2) Checkout do código
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3) Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 4) Build e Teste
      - name: Build & Test
        run: mvn -B clean verify

      # 5) Verificar se existe PR do hotfix para main
      - name: Check existing PR to main
        id: check_pr_main
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${{ github.event.inputs.hotfix_branch }}`,
              base: 'main',
              state: 'open'
            });
            
            if (prs.data.length > 0) {
              console.log(`PR já existe: #${prs.data[0].number}`);
              return prs.data[0].number;
            }
            return 0;

      # 6) Criar PR para main se não existir
      - name: Create PR to main if not exists
        id: create_pr_main
        if: steps.check_pr_main.outputs.result == 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.event.inputs.hotfix_branch }}
          title: "Hotfix: ${{ github.event.inputs.hotfix_branch }} to main"
          body: "Aplicando hotfix na main"
          delete-branch: false

      # 7) Merge do PR na main
      - name: Merge PR to main
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.check_pr_main.outputs.result != 0 && steps.check_pr_main.outputs.result || steps.create_pr_main.outputs.pull-request-number }}
          merge-method: squash

      # 8) Atualizar versão patch
      - name: Get current version
        id: get_version
        run: echo "current=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.get_version.outputs.current }}
          version-fragment: 'patch'

      # 9) Commit nova versão
      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.bump_version.outputs.next-version }} -DgenerateBackupPoms=false

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore: bump version to ${{ steps.bump_version.outputs.next-version }}"
          push_options: '--force'

      # 10) Criar e push tag
      - name: Create and push tag
        run: |
          git tag -a "v${{ steps.bump_version.outputs.next-version }}" -m "Release ${{ steps.bump_version.outputs.next-version }}"
          git push origin "v${{ steps.bump_version.outputs.next-version }}"

      # 11) Criar PR do commit da main para develop
      - name: Create PR to develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: main
          title: "Sync: main to develop (version ${{ steps.bump_version.outputs.next-version }})"
          body: "Sincronizando alterações da main para develop"
          delete-branch: false

      # 12) Merge do PR na develop
      - name: Merge PR to develop
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr_develop.outputs.pull-request-number }}
          merge-method: squash

      # 13) Build e push Docker
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_REPO }}:${{ steps.bump_version.outputs.next-version }}
            ${{ env.REGISTRY_REPO }}:latest
